#!/bin/bash

# Make sure we're in workdir
cd $(dirname "$BASH_SOURCE")

# This will ensure if any of sub-shells fail,
# this shell will fail too (thus not continue).
set -e

# Test
pytest --verbose -s --junitxml=./tests/test_results.xml $@
